name: DevSecOps Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-secure:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Download the code from the GitHub Vault
      - name: Check out the code
        uses: actions/checkout@v3

      # Step 2: Build the Docker image
      - name: Build the Docker image
        run: docker build -t my-nginx-app:latest .

      # Step 3: Run the Trivy X-Ray scan (The Bouncer / Policy-as-Code Gate)
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'my-nginx-app:latest'
          format: 'table'
          exit-code: '1' # Kills the pipeline if it finds a CRITICAL vulnerability
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      # Step 4: Generate the SBOM (The Ingredient List)
      - name: Generate SBOM
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'my-nginx-app:latest'
          format: 'cyclonedx'
          output: 'trivy-sbom.json'