name: DevSecOps Pipeline

on:
  push:
    branches:
      - main

# Give the robot permission to upload packages to your GitHub account
permissions:
  contents: read
  packages: write

jobs:
  build-and-secure:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v3

      # Build and tag the image with your specific GitHub Registry URL
      - name: Build the Docker image
        run: docker build -t ghcr.io/${{ github.repository_owner }}/secure-website:latest .

      # The Bouncer: Will kill the pipeline if it finds CRITICAL vulns
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'ghcr.io/${{ github.repository_owner }}/secure-website:latest'
          format: 'table'
          exit-code: '1' 
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      # The Ingredient List
      - name: Generate SBOM
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'ghcr.io/${{ github.repository_owner }}/secure-website:latest'
          format: 'cyclonedx'
          output: 'trivy-sbom.json'

      # NEW: Kubescape CIS Benchmark Check (The Inspector)
      - name: Run Kubescape CIS Benchmark scan
        uses: kubescape/github-action@main
        continue-on-error: true
        with:
          files: "k8s-deployment.yml"
          frameworks: "cis"
          

      # NEW: Log into the Garage
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # NEW: Park the Image in the Garage
      - name: Push image to Cloud Registry
        run: docker push ghcr.io/${{ github.repository_owner }}/secure-website:latest